<a href="https://colab.research.google.com/github/lalithanjalivavilapalli2109/FDS-DATASET/blob/main/FDS_lab_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df1 = pd.DataFrame({
    'Student_ID': [101, 102, 103, 104, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Department': ['CSE', 'ECE', 'CSE', 'IT', 'ECE'],
    'CGPA': [8.5, 7.8, 9.1, 8.2, 7.5]
})

df1

   Student_ID     Name Department  CGPA
0         101    Alice        CSE   8.5
1         102      Bob        ECE   7.8
2         103  Charlie        CSE   9.1
3         104    David         IT   8.2
4         105      Eva        ECE   7.5

In [ ]:
df2 = pd.DataFrame({
    'Student_ID': [101, 102, 103, 106, 107],
    'Marks': [85, 78, 92, 88, 75],
    'Grade': ['A', 'B', 'A+', 'A', 'B']
})

df2

   Student_ID  Marks Grade
0         101     85     A
1         102     78     B
2         103     92    A+
3         106     88     A
4         107     75     B

In [ ]:
df_hierarchical = df1.set_index(['Department', 'Student_ID'])

df_hierarchical

                          Name  CGPA
Department Student_ID
CSE        101           Alice   8.5
ECE        102             Bob   7.8
CSE        103         Charlie   9.1
IT         104           David   8.2
ECE        105             Eva   7.5

In [ ]:
df_hierarchical.loc['CSE']

               Name  CGPA
Student_ID
101           Alice   8.5
103         Charlie   9.1

In [ ]:
df_a = pd.DataFrame({
    'Name': ['A', 'B'],
    'Marks': [80, 85]
})

df_b = pd.DataFrame({
    'Name': ['C', 'D'],
    'Marks': [90, 75]
})

combined_vertical = pd.concat([df_a, df_b], ignore_index=True)

combined_vertical

  Name  Marks
0    A     80
1    B     85
2    C     90
3    D     75

In [ ]:
df_c = pd.DataFrame({
    'Name': ['A', 'B', 'C']
})

df_d = pd.DataFrame({
    'Marks': [80, 85, 90]
})

combined_horizontal = pd.concat([df_c, df_d], axis=1)

combined_horizontal

  Name  Marks
0    A     80
1    B     85
2    C     90

In [ ]:
merged_df = pd.merge(
    df1,
    df2,
    on='Student_ID',
    how='inner'
)

merged_df

   Student_ID     Name Department  CGPA  Marks Grade
0         101    Alice        CSE   8.5     85     A
1         102      Bob        ECE   7.8     78     B
2         103  Charlie        CSE   9.1     92    A+

In [ ]:
left_merge = pd.merge(
    df1,
    df2,
    on='Student_ID',
    how='left'
)

left_merge

   Student_ID     Name Department  CGPA  Marks Grade
0         101    Alice        CSE   8.5   85.0     A
1         102      Bob        ECE   7.8   78.0     B
2         103  Charlie        CSE   9.1   92.0    A+
3         104    David         IT   8.2    NaN   NaN
4         105      Eva        ECE   7.5    NaN   NaN

In [ ]:
outer_merge = pd.merge(
    df1,
    df2,
    on='Student_ID',
    how='outer'
)

outer_merge

   Student_ID     Name Department  CGPA  Marks Grade
0         101    Alice        CSE   8.5   85.0     A
1         102      Bob        ECE   7.8   78.0     B
2         103  Charlie        CSE   9.1   92.0    A+
3         104    David         IT   8.2    NaN   NaN
4         105      Eva        ECE   7.5    NaN   NaN
5         106      NaN        NaN   NaN   88.0     A
6         107      NaN        NaN   NaN   75.0     B

In [ ]:
melted_df = pd.melt(
    df1,
    id_vars=['Student_ID', 'Name'],
    value_vars=['Department', 'CGPA'],
    var_name='Attribute',
    value_name='Value'
)

melted_df

   Student_ID     Name   Attribute Value
0         101    Alice  Department   CSE
1         102      Bob  Department   ECE
2         103  Charlie  Department   CSE
3         104    David  Department    IT
4         105      Eva  Department   ECE
5         101    Alice        CGPA   8.5
6         102      Bob        CGPA   7.8
7         103  Charlie        CGPA   9.1
8         104    David        CGPA   8.2
9         105      Eva        CGPA   7.5

In [ ]:
pivot_table = pd.pivot_table(
    df1,
    values='CGPA',
    index='Department',
    aggfunc='mean'
)

pivot_table

            CGPA
Department
CSE         8.80
ECE         7.65
IT          8.20

In [ ]:
pivot_table2 = pd.pivot_table(
    df1,
    values='CGPA',
    index='Department',
    columns='Name',
    aggfunc='mean'
)

pivot_table2

Name        Alice  Bob  Charlie  David  Eva
Department
CSE           8.5  NaN      9.1    NaN  NaN
ECE           NaN  7.8      NaN    NaN  7.5
IT            NaN  NaN      NaN    8.2  NaN

In [ ]:
stacked = df1.set_index(['Student_ID', 'Name'])[['CGPA']].stack()

stacked

Student_ID  Name
101         Alice    CGPA    8.5
102         Bob      CGPA    7.8
103         Charlie  CGPA    9.1
104         David    CGPA    8.2
105         Eva      CGPA    7.5
dtype: float64

In [ ]:
unstacked = stacked.unstack()

unstacked

                    CGPA
Student_ID Name
101        Alice     8.5
102        Bob       7.8
103        Charlie   9.1
104        David     8.2
105        Eva       7.5

In [ ]:
sorted_df = df1.sort_values(
    by='CGPA',
    ascending=False
)

sorted_df

   Student_ID     Name Department  CGPA
2         103  Charlie        CSE   9.1
0         101    Alice        CSE   8.5
3         104    David         IT   8.2
1         102      Bob        ECE   7.8
4         105      Eva        ECE   7.5

In [ ]:
grouped_df = df1.groupby('Department')['CGPA'].mean()

grouped_df

Department
CSE    8.80
ECE    7.65
IT     8.20
Name: CGPA, dtype: float64

In [ ]:
print("Original DataFrame:")
display(df1)

print("\nMerged DataFrame:")
display(merged_df)

print("\nHierarchical Index:")
display(df_hierarchical)

print("\nPivot Table:")
display(pivot_table)

print("\nReshaped DataFrame:")
display(melted_df)

Original DataFrame:

   Student_ID     Name Department  CGPA
0         101    Alice        CSE   8.5
1         102      Bob        ECE   7.8
2         103  Charlie        CSE   9.1
3         104    David         IT   8.2
4         105      Eva        ECE   7.5

Merged DataFrame:

   Student_ID     Name Department  CGPA  Marks Grade
0         101    Alice        CSE   8.5     85     A
1         102      Bob        ECE   7.8     78     B
2         103  Charlie        CSE   9.1     92    A+

Hierarchical Index:

                          Name  CGPA
Department Student_ID
CSE        101           Alice   8.5
ECE        102             Bob   7.8
CSE        103         Charlie   9.1
IT         104           David   8.2
ECE        105             Eva   7.5

Pivot Table:

            CGPA
Department
CSE         8.80
ECE         7.65
IT          8.20

Reshaped DataFrame:

   Student_ID     Name   Attribute Value
0         101    Alice  Department   CSE
1         102      Bob  Department   ECE
2         103  Charlie  Department   CSE
3         104    David  Department    IT
4         105      Eva  Department   ECE
5         101    Alice        CGPA   8.5
6         102      Bob        CGPA   7.8
7         103  Charlie        CGPA   9.1
8         104    David        CGPA   8.2
9         105      Eva        CGPA   7.5